// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekasbrdkbafhhxmuopjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrYXNicmRrYmFmaGh4bXVvcGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDM3ODgsImV4cCI6MjA2MjgxOTc4OH0.3aNCBN6ys4QqtyX4B_iuVKsqovgH4t9YHIXpgmgDnO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);